### ISSUE TITLE
[Tracking] TWC 1.0 release

### ISSUE THREAD

**Issue by Akhliskun** [Akhliskun/taskcluster-worker-checker#114]
# Introduction
With TaskCluster Worker Checker growing to be more than just a tool used by CiDuty, we have to rethink how we handle logic, defs, code and many areas of the tool.

We also have a lot of areas that we can now remove and retire. Below will be a rough outline of what we need to do:

# Where?
All work will be done on branch `twc1.0`

# ToDo

- [ ] Finish implementation of GoogleAPI
- [ ] Remove machines_to_ignore = {...dictionary...}
- [ ] Rewrite parse_taskcluster_json()
- [ ] Remove generate_machine_lists()
- [ ] Put Google Auth login in a def
- [ ] Rewrite def main() and break it into smaller defs
- [ ] Implement UnitTesting
- [ ] When ready to release, Lock prior `master` code under version tag 0.9
