### ISSUE TITLE
[Core] User customization via userSettings.json

### ISSUE THREAD

**Issue by Akhliskun** [Akhliskun/taskcluster-worker-checker#133]
A lot of hardcoded values and default variable values can be moved to a userSettings.json file.
This will give users the ability to customize TWC to do more based on their own PC configuration.

## ToDo:

- [ ] Change iLO installation path
- [ ] Click coordinates per display.
- [ ] Store iLO password in a MD5 encrypted format, using the PC's unique ID as salt-password
- [ ] Rename configuration to run_flags.py
